// AUTO-GENERATED by scripts/generate-image-manifest.js — do not edit by hand.
// Run `npm run generate:images` (or any npm script that depends on it) to refresh.

export const IMAGE_MANIFEST: Record<string, readonly string[]> = {
  "dad-mode": [
    "assets/img/dad-mode-1.jpg",
    "assets/img/dad-mode-2.jpg",
    "assets/img/dad-mode-3.jpg",
    "assets/img/dad-mode-4.jpg",
    "assets/img/dad-mode-5.jpg"
  ],
  "florida": [
    "assets/img/florida-1.jpg",
    "assets/img/florida-2.jpg"
  ],
  "house": [
    "assets/img/house-1.jpg",
    "assets/img/house-2.jpg"
  ],
  "marathon": [
    "assets/img/marathon-1.jpg",
    "assets/img/marathon-2.jpg",
    "assets/img/marathon-3.jpg",
    "assets/img/marathon-4.jpg"
  ],
  "moto": [
    "assets/img/moto-1.jpg",
    "assets/img/moto-2.jpg",
    "assets/img/moto-3.jpg",
    "assets/img/moto-4.jpg"
  ],
  "nxtStudio": [
    "assets/img/nxtStudio-1.jpg"
  ],
  "rfs": [
    "assets/img/rfs-1.jpg",
    "assets/img/rfs-2.jpg"
  ],
  "slot-machine": [
    "assets/img/slot-machine-1.jpg",
    "assets/img/slot-machine-2.jpg",
    "assets/img/slot-machine-3.jpg",
    "assets/img/slot-machine-4.jpg"
  ],
  "spartan": [
    "assets/img/spartan-1.jpg",
    "assets/img/spartan-2.jpg"
  ],
  "the-boi": [
    "assets/img/the-boi-1.jpg",
    "assets/img/the-boi-2.jpg",
    "assets/img/the-boi-3.jpg",
    "assets/img/the-boi-4.jpg",
    "assets/img/the-boi-5.jpg"
  ],
  "vicnet": [
    "assets/img/vicnet-1.webp",
    "assets/img/vicnet-2.webp",
    "assets/img/vicnet-3.webp",
    "assets/img/vicnet-4.webp",
    "assets/img/vicnet-5.webp",
    "assets/img/vicnet-6.webp"
  ],
  "victouch": [
    "assets/img/victouch-1.webp",
    "assets/img/victouch-2.webp",
    "assets/img/victouch-3.webp",
    "assets/img/victouch-4.webp",
    "assets/img/victouch-5.webp"
  ],
  "wedding": [
    "assets/img/wedding-1.jpg",
    "assets/img/wedding-2.jpg",
    "assets/img/wedding-3.jpg"
  ],
  "workout": [
    "assets/img/workout-1.jpg",
    "assets/img/workout-2.jpg",
    "assets/img/workout-3.jpg"
  ]
} as const;
